[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
user=root
environment=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[program:dropbear]
command=/usr/local/sbin/dropbear -F -E -R -p 127.0.0.1:2200 -b /app/core/dropbear/banner.txt -K 60
autostart=true
autorestart=true
redirect_stderr=true

[program:openssh]
command=/usr/sbin/sshd -D -e -f /app/core/openssh/sshd_config
autostart=true
autorestart=true
redirect_stderr=true

[program:badvpn]
command=/usr/local/bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --loglevel warning --max-clients 1000 --max-connections-for-client 1024
autostart=true
autorestart=true
redirect_stderr=true

[program:xray]
command=/usr/local/bin/xray -config /etc/xray/config.json
autostart=true
autorestart=true
redirect_stderr=true

[program:singbox]
command=/usr/local/bin/sing-box run -c /etc/singbox/config.json
autostart=true
autorestart=true
redirect_stderr=true

[program:bridge_ssh]
command=/app/custom-tools/wait-for.sh 127.0.0.1:2200 -- python3 /app/relay/bridge.py 2222 127.0.0.1 2200 ssh
autostart=true
autorestart=true
redirect_stderr=true

[program:caddy]
command=/app/custom-tools/wait-for.sh 127.0.0.1:10001 -- caddy run --config /run/cfg/connector/caddy/Caddyfile --adapter caddyfile
autostart=true
autorestart=true
redirect_stderr=true

[program:nginx]
command=/app/custom-tools/wait-for.sh 127.0.0.1:10001 -- nginx -c /run/cfg/connector/nginx/nginx.conf -g "daemon off;"
autostart=true
autorestart=true
redirect_stderr=true

[program:haproxy]
command=/app/custom-tools/wait-for.sh 127.0.0.1:8083 127.0.0.1:8084 -- haproxy -f /run/cfg/connector/haproxy/haproxy.cfg -db
autostart=true
autorestart=true
redirect_stderr=true

[program:envoy]
command=/app/custom-tools/wait-for.sh 127.0.0.1:8082 -- envoy -c /run/cfg/connector/envoy/envoy.yaml --concurrency 2
autostart=true
autorestart=true
redirect_stderr=true

[program:fortress]
command=/app/custom-tools/wait-for.sh 127.0.0.1:8081 -- python3 /app/relay/fortress.py
autostart=true
autorestart=true
redirect_stderr=true
